spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    config-url: /${spring.application.name}${server.servlet.context-path}/v3/api-docs/swagger-config
    url: /${spring.application.name}${server.servlet.context-path}/v3/api-docs
jstorage:
  client:
    url: ${GATEWAY_HOST}/storage/api/v1
jaccount:
  activity-time: ${ACTIVITY_TIME:10m}
  offline-after-time: ${OFFLINE_AFTER_TIME:10m}
  service:
    host: ${GATEWAY_HOST}/${spring.application.name}${server.servlet.context-path}